services:
  app:
    build: .
    container_name: fast_api_template_prod
    env_file: ./.env
    ports:
      - $API_PORT:$DOCKER_PORT
    environment:
      - DEV_ENV=production
    command: uvicorn main:app --host 0.0.0.0 --port $DOCKER_PORT
