services:
  app:
    build: .
    container_name: fast_api_template
    env_file: ./.env
    ports:
      - $API_PORT:$DOCKER_PORT
    environment:
      - DEV_ENV=development
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port $DOCKER_PORT --reload
